apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- mysql-secret.yaml
- mysql-service.yaml
- mysql-statefulset.yaml
- app-deployment.yaml
- app-service.yaml
- servicemonitor.yaml
- prometheus-rules.yaml
- alert-webhook.yaml
images:
- name: securingweb
  newName: ghcr.io/huyhoangtran05/prometheus-grafana
  newTag: c74785b622d39834d4028ebc2e064ee51ad3d90d
