apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: securingweb
  labels:
    app: mysql
stringData:
  MYSQL_ROOT_PASSWORD: "1234"
  MYSQL_DATABASE: "securingweb"
  MYSQL_USER: "app"
  MYSQL_PASSWORD: "apppass"

