apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: securingweb
  namespace: securingweb
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: securingweb-app
  namespaceSelector:
    matchNames:
      - securingweb
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s

